apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}
  db_url: {{ .Values.auth.dbUrl }}
  pgadmin-email: {{ .Values.pgadmin.email }}
  pgadmin-password: {{ .Values.pgadmin.password }}
