apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: {{ .Values.service.pgadminPort }}
      targetPort: 80
  type: {{ .Values.service.type }}
