apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.service.postgresPort }}
      targetPort: 5432
  type: {{ .Values.service.type }}
